---
- name: Install Apache Tomcat  Server
  hosts: 192.168.121.133
  become: true

  tasks:
  - name: Install Java
    yum:
      name: java
      state: latest
  - name: Download Apache Tomcat Server Package
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz
      dest: /root/Downloads
  - name: Extracting the  Apache Tomcat Server Tar File.
    unarchive:
      src: /root/Downloads/apache-tomcat-8.5.58.tar.gz
      dest: /root/Downloads/
      remote_src: yes
  - name: Downloading the The Jenkins.war file
    get_url:
      url: https://get.jenkins.io/war-stable/2.249.1/jenkins.war
      dest: /root/Downloads/apache-tomcat-8.5.58/webapps
  - name: Starting the Apache Tomcat Server Software
    shell: nohup /root/Downloads/apache-tomcat-8.5.58/bin/startup.sh
    
